# Don't put duplicate lines into history, ignore commands w/ initial space
HISTCONTROL=ignoredup:ignorespace
# History file location & size
HISTFILE=$HOME/.history
HISTFILESIZE=2000
HISTSIZE=1000

# Bash options: {{{
# Auto-correct typos
shopt -s cdspell
# Check hash before executing
shopt -s checkhash
# Check window size after each command, and update $LINES and $COLUMNS
shopt -s checkwinsize
# Save all lines of multiline commands
shopt -s cmdhist
# Include filenames that begin with '.' in filename expansion
shopt -s dotglob
# Append to history list. Allow editing of history substitution in readline
# buffer
shopt -s histappend histreedit histverify
# Don't search path for completions when on an empty line
shopt -s no_empty_cmd_completion
# Case insensitive filename matching
shopt -s nocaseglob
# Not supported in ancient OS X version of bash
if [ "${BASH_VERSION%.*}" \> "4.2" ]; then
  # CD into dir as command
  shopt -s autocd
  # Warn about stopped jobs before exiting
  shopt -s checkjobs
  # Replace directory names when doing tab completion
  shopt -s direxpand
  # Spell check on directory names
  shopt -s dirspell
  # Use ** for nice filename matching
  shopt -s globstar
fi
# }}}

# Simple prompt user@host:pwd $
PS1="\[\e[31m\]\u@\h\[\e[m\]:\[\e[33m\]\w\[\e[m\] \$ "

# FZF keybindings
if [ -f $HOME/.fzf.bash ]; then
  source $HOME/.fzf.bash
fi

# Load aliases
if [ -f $HOME/.aliases ]; then
  source $HOME/.aliases
fi

# Load OS-specific files
if [ "$OS" = "Darwin" ]; then
  if [ -f $HOME/.bashrc.osx ]; then
    source $HOME/.bashrc.osx
  fi
elif [ "$OS" = "Linux" ]; then
  if [ -f $HOME/.bashrc.linux ]; then
    source $HOME/.bashrc.linux
  fi
fi

# Load local file if present
if [ -f $HOME/.bashrc.local ]; then
  source $HOME/.bashrc.local
fi
