# Base16 Default Light - ncspot color config
# Chris Kempson (http://chriskempson.com)

[theme]
background = "#f8f8f8"
primary = "#383838"
secondary = "#e8e8e8"
title = "#282828"
playing = "#282828"
playing_bg = "#f8f8f8"
highlight = "#383838"
highlight_bg = "#d8d8d8"
error = "#383838"
error_bg = "#181818"
statusbar = "#f8f8f8"
statusbar_progress = "#282828"
statusbar_bg = "#282828"
cmdline = "#383838"
cmdline_bg = "#f8f8f8"
