#!/usr/bin/env bash
#
# Generate variable declarations based on machine attributes / settings
#
# Usage: create_local_profile > ~/.profile.local

set -euo pipefail
IFS=$'\n\t'

main() {
  local is_crostini
  local is_mac
  local is_docker
  local is_wsl
  local is_headless

  # TODO: Update to use deb822 format when Crostini supports it
  is_crostini=""
  is_mac=""
  is_docker=""
  is_wsl=""
  is_headless=""

  [[ -f /etc/apt/sources.list.d/cros.list ]] && is_crostini=1
  [[ ${OSTYPE:-} == 'darwin'* ]] && is_mac=1
  [[ -n "${IS_DOCKER:-}" || -f /.dockerenv ]] && is_docker=1
  [[ -d /run/WSL ]] && is_wsl=1

  # Default to headless in Crostini / Docker / Mac / WSL, even though GUI might be
  # possible, can always be overridden
  if [[ -n "${is_crostini}" || -n "${is_docker}" || -n "${is_mac}" || -n "${is_wsl}" || -z "${WAYLAND_DISPLAY:-}" ]]; then
    is_headless=1
  fi

  cat << PROFILE_TEMPLATE
# Generated $(date +%F)
export IS_CROSTINI="${is_crostini:-}"
export IS_DOCKER="${is_docker:-}"
export IS_MAC="${is_mac:-}"
export IS_WSL="${is_wsl:-}"
export IS_HEADLESS="${is_headless:-}"

# Affects bash prompt, which hides unless this is the username
# export DEFAULT_USERNAME=ffortes

# Enable if GitHub account has Copilot access
# export ENABLE_GITHUB_COPILOT=1

# Used for 'llm' and 'aider'
# export ANTHROPIC_API_KEY="xxxxxx"
# export GEMINI_API_KEY="xxxxxx"
# export LLM_GEMINI_KEY="\${GEMINI_API_KEY}"
# export LLM_MISTRAL_KEY="xxxxxx"
# export OPENAI_API_KEY="xxxxxx"
# export OPENROUTER_API_KEY="xxxxxx"

# Typescript language server can OOM on large codebases
# export MAX_TS_SERVER_MEMORY=32768
# Same, but for eslint and others
# export NODE_OPTIONS='--max_old_space_size=16384'

# For scrobbing via cmus
# export LISTENBRAINZ_AUTH_TOKEN="xxxxxx"
# export LIBRE_FM_USERNAME="fortes"
# export LIBRE_FM_PASSWORD="xxxxxx"
# export LIBRE_FM_SESSION_KEY="xxxxxx"

# Add machine-specific items below
# export BEETSDIR=/data/media/music/beets
# export LOCAL_ALBUM_DIR="$HOME/music"
PROFILE_TEMPLATE
}

if [[ "${BASH_VERSINFO:-0}" -ge 4 ]]; then
  main "${@}"
else
  # Ancient Mac Bash version does not support `@`
  main
fi
