#!/usr/bin/env bash
#
# Generate variable declarations based on machine attributes / settings
#
# Usage: create_local_profile > ~/.profile.local

set -euo pipefail
IFS=$'\n\t'

main() {
  local is_crostini
  local is_mac
  local is_docker
  local is_wsl
  local is_headless

  set +e
  is_crostini=$([[ -f /etc/apt/sources.list.d/cros.list ]] && printf 1)
  is_mac=$([[ ${OSTYPE:-} == 'darwin'* ]] && printf 1)
  is_docker=$([[ -n "${IS_DOCKER:-}" || -f /.dockerenv ]] && printf 1)
  is_wsl=$([[ -d /run/WSL ]] && printf 1)
  # Default to headless in Crostini / Docker / WSL, even though GUI might be
  # possible, can always be overridden
  is_headless=$([[ -n "${is_crostini}${is_docker}${is_mac}${is_wsl}" || \
    -z "${WAYLAND_DISPLAY:-}" ]] && printf 1)
  set -e

  cat <<PROFILE_TEMPLATE
# Generated $(date +%F)
export IS_CROSTINI="${is_crostini:-}"
export IS_DOCKER="${is_docker:-}"
export IS_MAC="${is_mac:-}"
export IS_WSL="${is_wsl:-}"
export IS_HEADLESS="${is_headless:-}"

# Enable if GitHub account has Copilot access
# export ENABLE_GITHUB_COPILOT=1

# Used for 'llm' command
# export ANTHROPIC_API_KEY="xxxxxx"
# export OPENAI_API_KEY="xxxxxx"

# Typescript language server can OOM on large codebases
# export MAX_TS_SERVER_MEMORY=32768

# For scrobbing via cmus
# export LISTENBRAINZ_AUTH_TOKEN="xxxxxx"
# export LIBRE_FM_USERNAME="fortes"
# export LIBRE_FM_PASSWORD="xxxxxx"
# export LIBRE_FM_SESSION_KEY="xxxxxx"

# Add machine-specific items below
# export BEETSDIR=/data/media/music/beets
# export LOCAL_ALBUM_DIR="$HOME/music"
PROFILE_TEMPLATE
}

if [[ "${BASH_VERSINFO:-0}" -ge 4 ]]; then
  main "${@}"
else
  # Ancient Mac Bash version does not support `@`
  main
fi
