#!/usr/bin/env bash
# Setup Debian unstable source and install packages
#
# Usage: debian_unstable_setup

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

declare dotfiles_root
dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

UNSTABLE_PACKAGES=()

debian_unstable_setup() {
  declare -r unstable_sources_list="/etc/apt/sources.list.d/debian-unstable.list"

  if [ ! -f "$unstable_sources_list" ]; then
    echo "Debian unstable sources list missing, adding (requires sudo)"
    echo "deb http://deb.debian.org/debian/ unstable main" \
      | sudo tee "$unstable_sources_list"
    echo "Decreasing priority of unstable packages"
    printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' \
      | sudo tee /etc/apt/preferences.d/limit-unstable

    echo "Unstable sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  echo "Installing unstable packages (requires sudo)"
  sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
    --fix-broken --no-install-recommends --target-release unstable \
    "${UNSTABLE_PACKAGES[@]}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  debian_unstable_setup
fi
