#!/usr/bin/env bash
# Install cargo packages
#
# Usage: install_cargo_packages

set -euo pipefail
IFS=$'\n\t'

CARGO_PACKAGES=(
  google-fitness1-cli
)

# shellcheck source=script/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

install_cargo_packages() {
  [[ $# -eq 0 ]] || {
    echo >&2 'Usage: install_cargo_packages (no arguments)'
    return 1
  }

  if ! command_exists cargo; then
    echo >&2 "⨯ cargo not installed"
    exit 1
  fi

  echo "Using $(cargo --version)"

  echo "Installing cargo packages …"
  for package in "${CARGO_PACKAGES[@]}"; do
    cargo install --locked --quiet "${package}"
  done

  echo "Cargo packages installed!"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_cargo_packages "${@}"
fi
