#!/usr/bin/env bash
# Install Flatpak packages via flathub on Debian systems.
#
# Usage: install_flatpak_packages

set -euo pipefail
IFS=$'\n\t'

# shellcheck source=./stowed-files/bash/.profile
declare dotfiles_root
dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load command_exists helper and local paths
. "${dotfiles_root}/stowed-files/bash/.profile"

FLATPAK_PACKAGES=(
  io.github.hrkfdn.ncspot
)

install_flatpak_packages() {
  if ! command_exists flatpak; then
    echo "⨯ flatpak not installed, installing (requires sudo)"
    sudo -E apt-get update -qq
    sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
      --fix-broken --no-install-recommends flatpak
  fi

  if [[ "$(flatpak remotes | grep -c flathub)" -eq 0 ]]; then
    echo "Adding flathub remote..."
    flatpak remote-add --user --if-not-exists \
      flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  fi

  echo "Updating Flatpak repositories..."
  flatpak update --user --assumeyes --noninteractive

  echo "Installing Flatpak packages ..."
  for package in "${FLATPAK_PACKAGES[@]}"; do
    [ -z "${package}" ] && continue
    echo -n "Installing ${package} ... "
    flatpak install --or-update --user --assumeyes --noninteractive \
      flathub "${package}"

    local friendly_name="${package##*.}"

    # Allow access to config files, need dotfiles directory since they're
    # symlinked via `stow`
    flatpak override --user --filesystem="xdg-config/${friendly_name}" "${package}"
    flatpak override --user --filesystem="${dotfiles_root}/stowed-files/${friendly_name}" "${package}"

    echo "done."
  done
  echo "Flatpak packages installed!"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_flatpak_packages "${@}"
fi
