#!/usr/bin/env bash
# Setup Eternal Terminal
#
# Usage: install_et

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

install_et() {
  declare -r et_sources_list="/etc/apt/sources.list.d/et.list"
  declare -r et_key_url="https://github.com/MisterTea/debian-et/raw/master/et.gpg"
  declare -r et_key_path="/etc/apt/keyrings/et.gpg"

  if [ ! -f "${et_sources_list}" ]; then
    echo "Adding Eternal Terminal GPG key (requires sudo)"
    curl -sSL "${et_key_url}" |
      sudo tee "$et_key_path" >/dev/null

    echo "Eternal Terminal sources list missing, adding (requires sudo)"
    echo "deb [signed-by=${et_key_path}] https://github.com/MisterTea/debian-et/raw/master/debian-source/ bookworm main" |
      sudo tee "${et_sources_list}" >/dev/null

    echo "Eternal Terminal sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  echo "Installing et package (requires sudo)"
  sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
    --fix-broken --no-install-recommends et
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_et "${@}"
fi
