#!/usr/bin/env bash
# Make your machine usable
#
# Usage: install_google_chrome

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

install_google_chrome() {
  declare -r chrome_installer_url="http://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  declare -r chrome_deb_temp_path="/tmp/zoom_amd64.deb"

  echo "Downloading latest Chrome .deb"
  wget "${chrome_installer_url}" -O "${chrome_deb_temp_path}"

  echo "Installing latest Chrome .deb (requires sudo)"
  sudo dpkg --install "${chrome_deb_temp_path}"
  rm -rf "${chrome_deb_temp_path}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_google_chrome "${@}"
fi
