#!/usr/bin/env bash
# Setup KVM
#
# Usage: install_kvm

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

install_kvm() {
  echo "Installing KVM packages (requires sudo)"

  declare packages=(
    dnsmasq-base
    libvirt-clients
    libvirt-daemon-system
    ovmf
    qemu-kvm
    qemu-utils
    virtinst
  )
  if [[ -z "${IS_HEADLESS:-}" ]]; then
    packages+=(virt-manager)
  fi

  sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
    --fix-broken --no-install-recommends \
    "${packages[@]}"

  # Can hit all sorts of polkit errors if you don't do this
  echo "Add user to libvirt group (requires sudo)"
  sudo usermod -a -G libvirt "$(whoami)"

  echo "Setup complete (but consider \`virsh net-autostart default\`)"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_kvm "${@}"
fi
