#!/usr/bin/env bash
# Install plugins for `yazi`
#
# Usage: install_yazi_plugins

set -euo pipefail
IFS=$'\n\t'

declare dotfiles_root
dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Helper function to check if command exists
command_exists() {
  command -v "$1" &> /dev/null
}

PLUGINS=(
  yazi-rs/plugins:git
)

install_yazi_plugins() {
  if ! command_exists ya; then
    >&2 echo "⨯ yazi not installed!"
    exit 1
  fi

  echo "Updating yazi plugins …"
  ya pack --upgrade
  for plugin in "${PLUGINS[@]}"; do
    if ! ya pack --list | grep -q "${plugin}"; then
      echo "Installing yazi plugin ${plugin}"
      ya pack --add "${plugin}"
    fi
  done
  echo "yazi plugins installed!"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_yazi_plugins "${@}"
fi
