#!/usr/bin/env bash
# Install 1password GUI app
#
# Usage: install_1password

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

install_1password() {
  declare -r op_sources_list="/etc/apt/sources.list.d/1password.sources"
  declare -r op_key_url="https://downloads.1password.com/linux/keys/1password.asc"
  declare -r op_debsig_url="https://downloads.1password.com/linux/debian/debsig/1password.pol"
  declare -r op_keyring_path="/usr/share/keyrings/1password-archive-keyring.gpg"
  declare -r op_id="AC2D62742012EA22"
  declare -r op_policy_path="/etc/debsig/policies/${op_id}/1password.pol"
  declare -r op_debsig_path="/usr/share/debsig/keyrings/${op_id}/debsig.gpg"
  declare -r architecture=$(dpkg --print-architecture)

  if [ ! -f "$op_sources_list" ]; then
    echo "Getting 1Password GPG key (requires sudo)"
    curl -sS ${op_key_url} | sudo -E gpg --dearmor --output ${op_keyring_path}

    echo "Adding 1Password sources list (requires sudo)"
    sudo tee "$op_sources_list" > /dev/null <<EOF
Types: deb
URIs: https://downloads.1password.com/linux/debian/${architecture}
Suites: stable
Components: main
Architectures: ${architecture}
Signed-By: ${op_keyring_path}
EOF

    echo "Adding signature keys"
    sudo mkdir -p "$(dirname ${op_policy_path})" "$(dirname ${op_debsig_path})"
    sudo cp ${op_keyring_path} ${op_debsig_path}
    curl -sS ${op_debsig_url} | sudo tee ${op_policy_path} > /dev/null

    echo "1Password sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  declare packages=()
  packages+=("1password-cli")
  if [[ -z "${IS_HEADLESS:-}" ]]; then
    packages+=("1password")
  fi

  echo "Installing" "${packages[@]}" "packages (requires sudo)"
  sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
    --fix-broken --no-install-recommends \
    "${packages[@]}" xdg-user-dirs

  echo "Generating bash completion"
  mkdir -p "$HOME/.local/completion.d"
  op completion bash > "$HOME/.local/completion.d/op_completion"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_1password "${@}"
fi
