#!/usr/bin/env bash
# Install Snap packages on Debian systems.
#
# Usage: install_snap_packages

set -euo pipefail
IFS=$'\n\t'

# shellcheck source=script/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

SNAP_PACKAGES=(
  marksman
)

install_snap_packages() {
  if [[ -n "${IS_DOCKER:-}" || -n "${IS_CROSTINI:-}" ]]; then
    echo "⨯ Snap packages cannot be installed in Docker or Crostini environments."
    return 1
  fi

  if ! command_exists snap; then
    echo "⨯ snap not installed, installing (requires sudo)"
    sudo -E apt-get update -qq
    sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
      --fix-broken --no-install-recommends snapd
  fi

  echo "Installing Snap packages ..."
  for package in "${SNAP_PACKAGES[@]}"; do
    [ -z "${package}" ] && continue
    echo -n "Installing ${package} ... "
    sudo snap install "${package}"
    echo "done."
  done
  echo "Snap packages installed!"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_snap_packages "${@}"
fi
