#!/usr/bin/env bash
# Setup Zoom Meetings client
#
# Usage: install_zoom

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

install_zoom() {
  declare -r zoom_deb_url="https://zoom.us/client/latest/zoom_amd64.deb"
  declare -r zoom_deb_temp_path="/tmp/zoom_amd64.deb"

  echo "Installing pre-requisites"
  sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
    --fix-broken --no-install-recommends libgl1-mesa-glx libxcb-xtest0 libegl1-mesa

  echo -n "Downloading latest Zoom .deb ... "
  wget -q "${zoom_deb_url}" -O "${zoom_deb_temp_path}"
  echo "Installing latest Zoom .deb (requires sudo)"
  sudo dpkg --install "${zoom_deb_temp_path}"
  rm -rf "${zoom_deb_temp_path}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_zoom
fi
