#!/usr/bin/env bash
# Install Flatpak packages via flathub on Debian systems.
#
# Usage: install_flatpak_packages

set -euo pipefail
IFS=$'\n\t'

declare dotfiles_root
dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load command_exists helper and local paths
. "${dotfiles_root}/stowed-files/bash/.profile"

install_flatpak_packages() {
  if ! command_exists flatpak; then
    >&2 echo "⨯ flatpak not installed!"
    exit 1
  fi

  if [[ "$(flatpak remotes | grep -c flathub)" -eq 0 ]]; then
    echo "Adding flathub remote..."
    flatpak remote-add --user --if-not-exists \
      flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  fi

  echo "Updating Flatpak repositories..."
  flatpak update -y

  local packages_file="${dotfiles_root}/script/flatpak-packages"
  if [[ ! -f "${packages_file}" ]]; then
    >&2 echo "⨯ Packages file ${packages_file} not found!"
    exit 1
  fi

  echo "Installing Flatpak packages from ${packages_file} ..."
  grep -v "^#" "${packages_file}" | while read -r package; do
    [ -z "${package}" ] && continue
    echo -n "Installing ${package} ... "
    flatpak install --or-update --user --assumeyes --noninteractive \
      flathub "${package}"

    local friendly_name="${package##*.}"
    if grep -vq "^alias ${friendly_name}=" "${HOME}/.aliases.local"; then
      echo -n "Adding alias for ${friendly_name} ..."
      echo "alias ${friendly_name}='flatpak run ${package}'" >> "${HOME}/.aliases.local"
    fi

    echo "done."
  done
  echo "Flatpak packages installed!"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_flatpak_packages "${@}"
fi
