#!/usr/bin/env bash
# Install VSCode
#
# Usage: install_vscode

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

declare dotfiles_root
dotfiles_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

install_vscdoe() {
  declare -r vscode_sources_list="/etc/apt/sources.list.d/vscode.sources"
  declare -r vscode_key_url="https://packages.microsoft.com/keys/microsoft.asc"
  declare -r vscode_key_path="/etc/apt/keyrings/microsoft.asc"

  if [ ! -f "$vscode_sources_list" ]; then
    echo "Adding Microsoft GPG key (requires sudo)"
    curl -sS "$vscode_key_url" |
      sudo tee "$vscode_key_path" > /dev/null

    echo "Microsoft VSCode sources list missing, adding (requires sudo)"
    sudo tee "$vscode_sources_list" > /dev/null <<EOF
Types: deb
URIs: https://packages.microsoft.com/repos/vscode
Suites: stable
Components: main
Architectures: amd64
Signed-By: ${vscode_key_path}
EOF

    echo "Microsoft VSCode sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  if ! command -v code &> /dev/null; then
    echo "Installing code package (requires sudo)"
    sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
      --fix-broken --no-install-recommends code
  else
    echo "VSCode already installed, skipping"
  fi

  exec "${dotfiles_root}/script/install_vscode_extensions"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_vscdoe
fi
