#!/usr/bin/env bash
# Install Signal Desktop Client
#
# Usage: install_signal

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

install_signal() {
  declare -r signal_sources_list="/etc/apt/sources.list.d/signal-xenial.sources"
  declare -r signal_key_url="https://updates.signal.org/desktop/apt/keys.asc"
  declare -r signal_key_path="/etc/apt/keyrings/signal-xenial.asc"

  if [ ! -f "$signal_sources_list" ]; then
    echo "Adding signal GPG key (requires sudo)"
    curl -sS "$signal_key_url" \
      | sudo tee "$signal_key_path" >/dev/null

    echo "signal sources list missing, adding (requires sudo)"
    sudo tee "$signal_sources_list" >/dev/null <<EOF
Types: deb
URIs: https://updates.signal.org/desktop/apt
Suites: xenial
Components: main
Architectures: amd64
Signed-By: ${signal_key_path}
EOF

    echo "Signal sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  echo "Installing signal package (requires sudo)"
  sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
    --fix-broken --no-install-recommends signal-desktop desktop-file-utils
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_signal
fi
