#!/usr/bin/env bash
# Install Firefox
#
# Usage: install_firefox

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

install_firefox() {
  declare -r firefox_sources_list="/etc/apt/sources.list.d/firefox.sources"
  declare -r firefox_key_url="https://packages.mozilla.org/apt/repo-signing-key.gpg"
  declare -r firefox_key_path="/etc/apt/keyrings/packages.mozilla.org.asc"

  if [ ! -f "$firefox_sources_list" ]; then
    echo "Adding firefox GPG key (requires sudo)"
    curl -sS "$firefox_key_url" | sudo tee ${firefox_key_path} > /dev/null

    echo "firefox sources list missing, adding (requires sudo)"
    sudo tee "$firefox_sources_list" > /dev/null <<EOF
Types: deb
URIs: https://packages.mozilla.org/apt
Suites: mozilla
Components: main
Signed-By: ${firefox_key_path}
EOF

    echo "firefox sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  echo "Removing firefox-esr package (requires sudo)"
  sudo -E apt-get remove --quiet --assume-yes firefox-esr
  echo "Installing firefox package (requires sudo)"
  sudo -E apt-get install -qq -o=Dpkg::Use-Pty=0 --assume-yes \
    --fix-broken --no-install-recommends firefox
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_firefox "${@}"
fi
