#!/usr/bin/env bash
# Sets the default browser on Chromebooks, using the Chromebook's native
# browser (Garcon) on Crostini.

set -euo pipefail
IFS=$'\n\t'

set_default_browser() {
  local desired_browser_path
  local xdg_browser

  # Make sure to pick up `command_exists` and `IS_CROSTINI`
  # shellcheck source=/dev/null
  . "${HOME}/.profile"

  if ! command_exists update-alternatives; then
    >&2 echo "update-alternatives not found, skipping"
    exit 1
  fi

  if [[ -n "${IS_CROSTINI}" ]]; then
    desired_browser_path="$(command -v garcon-url-handler)"
    xdg_browser='garcon_host_browser.desktop'
  fi

  if [[ -z "${desired_browser_path:-}" ]]; then
    >&2 echo "No desired browser found, skipping"
    exit
  fi

  # Bail if `update-alternatives` isn't set up for x-www-browser, may want to
  # manually install options at some point, but for now ignore
  if ! update-alternatives --query x-www-browser &>/dev/null; then
    >&2 echo "update-alternatives not set for x-www-browser, skipping"
    exit
  fi

  local current_browser_path
  current_browser_path="$(
    update-alternatives --query x-www-browser | grep '^Value:' | cut -d' ' -f2
  )"

  if [[ "${current_browser_path}" != "${desired_browser_path}" ]]; then
    echo "Setting default browser to $(basename "${desired_browser_path}") (requires sudo)"
    sudo update-alternatives --set x-www-browser "${desired_browser_path}"
  fi
  if [[ -n "${xdg_browser}" ]] && xdg-settings get default-web-browser | grep -vq "${xdg_browser}"; then
    echo "Setting XDG default browser to ${xdg_browser}"
    BROWSER='' xdg-settings set default-web-browser "${xdg_browser}"
  fi

  echo "Default browser set to $(basename "${desired_browser_path}")"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  set_default_browser "${@}"
fi
