#!/usr/bin/env bash
# Sets the default browser on Chromebooks/WSL/Linux, using the Chromebook's
# native browser (Garcon) on Chromebooks, and Firefox on WSL/Linux.

set -euo pipefail
IFS=$'\n\t'

set_default_browser() {
  local desired_browser_path
  local xdg_browser

  # Make sure to pick up `command_exists`, as well as `IS_CROSTINI` and `IS_WSL`
  # shellcheck source=/dev/null
  . "${HOME}/.profile"

  if ! command_exists update-alternatives; then
    >&2 echo "update-alternatives not found, skipping"
    exit 1
  fi

  if [[ -n "${IS_CROSTINI}" ]]; then
    desired_browser_path=$(command -v garcon-url-handler)
    xdg_browser='garcon_host_browser.desktop'
  elif [[ -n "${IS_WSL}" ]]; then
    if [[ -x "/mnt/c/Program Files/Mozilla Firefox/firefox.exe" ]]; then
      desired_browser_path="/mnt/c/Program Files/Mozilla Firefox/firefox.exe"
    else
      >&2 echo "Firefox not found in WSL, using Edge as a fallback"
      desired_browser_path="/mnt/c/Program Files/Microsoft/Edge/Application/msedge.exe"
    fi
  else
    desired_browser_path=$(command -v firefox)
    xdg_browser='firefox.desktop'
  fi

  if [[ -z "${desired_browser_path}" ]]; then
    >&2 echo "No desired browser found, skipping"
    exit 1
  fi

  local current_browser_path
  current_browser_path="$(
    update-alternatives --query x-www-browser | grep '^Value:' | cut -d' ' -f2
  )"

  if [[ "${current_browser_path}" != "${desired_browser_path}" ]]; then
    echo "Setting default browser to $(basename "${desired_browser_path}") (requires sudo)"
    sudo update-alternatives --set x-www-browser "${desired_browser_path}"
  fi
  if [[ -n "${xdg_browser}" ]] && xdg-settings get default-web-browser | grep -vq "${xdg_browser}"; then
    echo "Setting XDG default browser to ${xdg_browser}"
    BROWSER='' xdg-settings set default-web-browser "${xdg_browser}"
  fi

  echo "Default browser set to $(basename "${desired_browser_path}")"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  set_default_browser "${@}"
fi
