#!/usr/bin/env bash
# Generate bash completion files for various tools
#
# Usage: generate_completions

# Pick up `command_exists`
# shellcheck source=../stowed-files/bash/.profile
source "${HOME}/dotfiles/stowed-files/bash/.profile"

generate_completions() {
  declare -r completion_dir="$HOME/.local/completion.d"
  echo -n "… Generating completions & man pages"
  mkdir -p "${completion_dir}"

  if command_exists npm; then
    npm completion > "${completion_dir}/npm_completion"
  fi

  if command_exists beet; then
    beet completion > "${completion_dir}/beet_completion"
  fi

  if command_exists gh; then
    gh completion -s bash > "${completion_dir}/gh_completion"
  fi

  if command_exists pipx; then
    register-python-argcomplete --shell bash pipx > "${completion_dir}/pipx_completion"
  fi

  if command_exists bun; then
    SHELL=bash bun completions "${completion_dir}" > "${completion_dir}/bun.completion.bash"
  fi

  if command_exists deno; then
    deno completions bash > "${completion_dir}/deno_completion"
  fi

  if command_exists fnm; then
    fnm completions > "${completion_dir}/fnm_completion"
  fi

  if command_exists yq; then
    yq shell-completion bash > "${completion_dir}/yq_completion"
  fi

  echo -e "\r\033[K✓ Completions generated"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  generate_completions "${@}"
fi
