#!/usr/bin/env bash
# Setup Zerotier
#
# Usage: install_zerotier

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

main() {
  declare -r zerotier_sources_list="/etc/apt/sources.list.d/zerotier.list"
  declare -r zerotier_key_url="https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg"
  declare -r zerotier_key_path="/etc/apt/keyrings/zerotier.asc"

  if [ ! -f "$zerotier_sources_list" ]; then
    echo "Adding Zerotier GPG key (requires sudo)"
    curl -sS "$zerotier_key_url" | \
      sudo tee "$zerotier_key_path" > /dev/null

    echo "Zerotier sources list missing, adding (requires sudo)"
    echo "deb [signed-by=${zerotier_key_path}] http://download.zerotier.com/debian/bookworm bookworm main" \
      | sudo tee "$zerotier_sources_list" > /dev/null

    echo "Zerotier sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  echo "Installing zerotier package (requires sudo)"
  sudo -E apt-get install -qq --assume-yes \
    --fix-broken --no-install-recommends zerotier-one

  echo 'Join network via `sudo zerotier-cli join xxxxxxxxx`'
}

main
