#!/usr/bin/env bash
# Setup GitHub CLI utility
#
# Usage: setup_github_cli

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

main() {
  declare -r github_cli_sources_list='/etc/apt/sources.list.d/github_cli.list'

  if [ ! -f "$github_cli_sources_list" ]; then
    echo "Adding GitHub CLI GPG key (requires sudo)"
    sudo apt-key adv --keyserver keyserver.ubuntu.com \
      --recv-key C99B11DEB97541F0

    echo "GitHub CLI sources list missing, adding (requires sudo)"
    echo "deb https://cli.github.com/packages bullseye main" \
      | sudo tee "$github_cli_sources_list"

    echo "GitHub CLI sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  echo "Installing gh package (requires sudo)"
  sudo -E apt-get install -qq --assume-yes \
    --fix-broken --no-install-recommends gh
}

main
