#!/usr/bin/env bash
# Setup KVM
#
# Usage: setup_kvm

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

main() {
  echo "Installing KVM packages (requires sudo)"

  declare packages="qemu-kvm qemu-utils libvirt-clients libvirt-daemon-system virtinst dnsmasq-base ovmf"
  if [[ -z "${IS_HEADLESS:-}" ]]; then
    packages="${packages} virt-manager"
  fi

  sudo -E apt-get install -qq --assume-yes \
    --fix-broken --no-install-recommends \
    ${packages}

  # Can hit all sorts of polkit errors if you don't do this
  echo "Add user to libvirt group (requires sudo)"
  sudo usermod -a -G libvirt "$(whoami)"

  echo "Setup complete (but consider \`virsh net-autostart default\`)"
}

main
