#!/usr/bin/env bash
# Setup Debian unstable source and install packages
#
# Usage: setup_debian_unstable

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

main() {
  declare -r zerotier_sources_list="/etc/apt/sources.list.d/zerotier.list"
  declare -r zerotier_key_url="https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg"

  if [ ! -f "$zerotier_sources_list" ]; then
    echo "Adding Zerotier GPG key (requires sudo)"
    curl -sS "$zerotier_key_url" | sudo -E apt-key add -

    echo "Zerotier sources list missing, adding (requires sudo)"
    echo "deb http://download.zerotier.com/debian/buster buster main" \
      | sudo tee "$zerotier_sources_list"

    echo "Unstable sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  echo "Installing zerotier package (requires sudo)"
  sudo -E apt-get install -qq --assume-yes \
    --fix-broken --no-install-recommends zerotier-one
}

main
