#!/usr/bin/env bash
# Install fnm  (Node version manager)
#
# Usage `setup_fnm`

set -euo pipefail
IFS=$'\n\t'

main() {
  local filename="fnm-linux"
  case "$(uname -m)" in
    arm | armv7)
      filename="fnm-arm32c"
      ;;
    aarch* | armv8)
      filename="fnm-arm64"
      ;;
  esac

  local url="https://github.com/Schniz/fnm/releases/latest/download/${filename}.zip"

  local download_dir=$(mktemp -d)
  echo "Downloading fnm ${filename}.zip"

  if ! curl --progress-bar --fail -L "$url" -o "${download_dir}/${filename}.zip"; then
    echo "Download failed!"
    return 1
  fi

  echo "Unzipping"
  unzip -q "${download_dir}/${filename}.zip" -d "${download_dir}"

  mv "${download_dir}/fnm" "$HOME/.local/bin/fnm"
  chmod u+x "$HOME/.local/bin/fnm"

  echo "fnm installed. Generating completions"
  "$HOME/.local/bin/fnm" completions > "$HOME/.local/completion.d/fnm_completion"

  echo "Complete!"
}

main
