#!/usr/bin/env bash
# Setup Lutris for games
#
# Usage: setup_lutris

set -euo pipefail
IFS=$'\n\t'
export DEBIAN_FRONTEND=noninteractive

main() {
  declare -r lutris_sources_list="/etc/apt/sources.list.d/lutris.list"
  declare -r lutris_key_url="https://download.opensuse.org/repositories/home:/strycore/Debian_12/Release.key"
  declare -r lutris_key_path="/etc/apt/keyrings/lutris.gpg"

  if [ ! -f "$lutris_sources_list" ]; then
    echo "Adding Lutris GPG key (requires sudo)"
    curl -sS ${lutris_key_url} | \
      sudo -E gpg --dearmor --output ${lutris_key_path}

    echo "Lutris sources list missing, adding (requires sudo)"
    echo "deb [signed-by=${lutris_key_path}] https://download.opensuse.org/repositories/home:/strycore/Debian_12/ ./" \
      | sudo tee "$lutris_sources_list" > /dev/null

    echo "Lutris sources added, updating packages"
    sudo -E apt-get update -qq
  fi

  # Force IPv4 for now
  echo "Installing lutris package (requires sudo)"
  sudo -E apt-get install -qq --assume-yes \
    --fix-broken \
    -o Acquire::ForceIPv4=true \
    lutris
}

main
